### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @xinntao ! 👋 

Appreciated your feedback on the previous PR. It has been modified accordingly in this PR.

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.ai/xinntao/gfpgan
(We noticed that you have a demo on Gradio, but some of the example images, e.g. 10045.png, would show error there).
 
[Claim your page here](https://replicate.ai/login/github/?next=/xinntao/gfpgan?published=1) so you can edit it, and we'll feature it on our website and tweet about it too.

In case you're wondering who I am, I'm from [Replicate](https://replicate.ai/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Review by initpwn — APPROVED** [review]

**Comment by marcellodesales** [comment]
# No Dockerfile

* I don't see anything in this PR :)
* To me, Docker environment is when I can do `docker-compose up --build` 

As an Engineer who depends on Docker, I don't think this is it... Maybe rename the PR to something else? It's just misleading...

It's only my 2c

**Comment by CJWBW** [comment]
> # No Dockerfile
> 
> 
> 
> * I don't see anything in this PR :)
> 
> * To me, Docker environment is when I can do `docker-compose up --build` 
> 
> 
> 
> As an Engineer who depends on Docker, I don't think this is it... Maybe rename the PR to something else? It's just misleading...
> 
> 
> 
> It's only my 2c
> 
> 
> 
> # Edit
> 
> 
> 
> This is a Dockerized solution https://github.com/TencentARC/GFPGAN/pull/103

You can find the docker file under 'Run model with Docker' tab https://replicate.com/xinntao/gfpgan

Cog is built on top of Docker.

**Comment by marcellodesales** [comment]
@CJWBW Can you please provide the `Dockerfile` in the project so we can all inspect what's inside?

The Docker Image at r8.im/xinntao/gfpgan@sha256:fec8c51c3017f1afbf8b0eed7f4ba51158e49b527b92aea91833aed32559e2ef is extremely huge

```console
$ docker pull r8.im/xinntao/gfpgan@sha256:fec8c51c3017f1afbf8b0eed7f4ba51158e49b527b92aea91833aed32559e2ef
r8.im/xinntao/gfpgan@sha256:fec8c51c3017f1afbf8b0eed7f4ba51158e49b527b92aea91833aed32559e2ef: Pulling from xinntao/gfpgan
be8ec4e48d7f: Pull complete
33b8b485aff0: Pull complete
d887158cc58c: Pull complete
05895bb28c18: Pull complete
3d2964768f60: Pull complete
879de1f9d3b9: Pull complete
4e56b74a6bb6: Pull complete
b6074c21aee0: Downloading [===========>                                       ]  337.9MB/1.501GB
ef6ce9582f59: Downloading [============>                                      ]  318.4MB/1.232GB
ab542382d70b: Downloading [==========>                                        ]  316.3MB/1.568GB
8e6b9d4be9a9: Waiting
930d70c29689: Waiting
```

Please provide the original Dockerfile for transparency... 

thank you
Marcello

**Comment by marcellodesales** [comment]
# Cog architecture

* I think it's worthwhile to include a reference to the docs at https://github.com/replicate/cog/blob/main/docs/getting-started-own-model.md
* At first, one can imagine we don't need cog
* I would reason on the following: Using a Web Server to serve is great and it maintains a nice interface
  * However, Docker is all microservices and small units of work... 
  * I would split the Web Server from the Machine learning `predict.py` 

I think there's some benefits to this... I'm trying to wrap my head around and be able to use it... Cog will also allow running the model in the CLI... This is another reason why I could see splitting the CLI container from the Web as any Containerized cloud-native service would do... Yet, I'm balanced to say this would satisfy my need at the moment... I will keep digging more and those are my 3c.

**Comment by xinntao** [comment]
@chenxwh 
Sorry for the very late merge and reply :-)

May I know how can I update the demo in https://replicate.com/tencentarc/gfpgan?
Just modify the file in predict.py?

**Comment by chenxwh** [comment]
> May I know how can I update the demo in https://replicate.com/tencentarc/gfpgan? Just modify the file in predict.py?

Hi @xinntao,

Sure! With `cog login` to you replicate account, and then `cog push  r8.im/tencentarc/gfpgan` you can push any changes to the web page. Note that all the files including the weights should be in the directory when you do the push. 

More documentation can be found [here](https://github.com/replicate/cog).

Let me know if you need further clarification :)

**Comment by xinntao** [comment]
> > May I know how can I update the demo in https://replicate.com/tencentarc/gfpgan? Just modify the file in predict.py?
> 
> Hi @xinntao,
> 
> Sure! With `cog login` to you replicate account, and then `cog push r8.im/tencentarc/gfpgan` you can push any changes to the web page. Note that all the files including the weights should be in the directory when you do the push.
> 
> Sometimes it may be easier to pull the docker image already up for the demo and only make corresponding changes in `predict.py`, please refer to [this](https://github.com/gwang-kim/DiffusionCLIP/pull/15#issuecomment-1211737126) for how it can be done.
> 
> More documentation about Cog can be found [here](https://github.com/replicate/cog).
> 
> Let me know if you need further clarification :)

Hi @chenxwh 
When I push changes to `cog push r8.im/tencentarc/gfpgan`, it shows that I do not have the write access to the model. 
Is there anything I should  modify?

**Comment by xinntao** [comment]
> > May I know how can I update the demo in https://replicate.com/tencentarc/gfpgan? Just modify the file in predict.py?
> 
> Hi @xinntao,
> 
> Sure! With `cog login` to you replicate account, and then `cog push r8.im/tencentarc/gfpgan` you can push any changes to the web page. Note that all the files including the weights should be in the directory when you do the push.
> 
> Sometimes it may be easier to pull the docker image already up for the demo and only make corresponding changes in `predict.py`, please refer to [this](https://github.com/gwang-kim/DiffusionCLIP/pull/15#issuecomment-1211737126) for how it can be done.
> 
> More documentation about Cog can be found [here](https://github.com/replicate/cog).
> 
> Let me know if you need further clarification :)

Hi @chenxwh 

I have updated the replicate ai demo: `https://replicate.com/tencentarc/gfpgan`. And it has over 225,016 runs.
This PR has also been merged. 
Can you help to feature the gfpgan model on your replicate.ai homepage and more people can view and try it?

**Comment by andreasjansson** [comment]
Hi @xinntao, Andreas from Replicate here. Really great work with GFPGAN, it's such a cool model! I've featured it on the home page.

If you'd like to chat in real-time, the Replicate Discord server is here: https://discord.gg/replicate. Would love to have you in our community!

**Comment by andreafalzetti** [comment]
Why is there only v1.2 and v1.3 on Replciate?

**Pull request merged**
